# Generated by Django 2.2.14 on 2020-10-06 08:21

import book.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=127)),
                ('last_name', models.CharField(max_length=127)),
                ('date_of_birth', models.DateField(validators=[book.validators.date_should_be_in_past_validator])),
                ('date_of_death', models.DateField(blank=True, null=True, validators=[book.validators.date_should_be_in_past_validator])),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=64)),
                ('gender', models.BooleanField(blank=True, help_text='True if male, False if female, Null is unknown', null=True)),
                ('language', models.CharField(max_length=64)),
                ('created_by_student', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('publish_year', models.PositiveSmallIntegerField(validators=[book.validators.year_validator])),
                ('created_by_student', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Author')),
            ],
        ),
    ]
